project_id = "rtrmbxfvdtenrcpmkvhu"

[functions.analyze-expressions]
verify_jwt = false

[functions.generate-clay]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.generate-pose-single]
verify_jwt = false

[functions.generate-poses]
verify_jwt = false

[functions.organize-images]
verify_jwt = false

[functions.scrape-brand]
verify_jwt = false
