project_id = "rtrmbxfvdtenrcpmkvhu"

[functions.analyze-expressions]
verify_jwt = false

[functions.generate-clay]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.generate-pose-single]
verify_jwt = false

[functions.generate-poses]
verify_jwt = false

[functions.organize-images]
verify_jwt = false

[functions.organize-clay-poses]
verify_jwt = false

[functions.organize-clay-single]
verify_jwt = false

[functions.scrape-brand]
verify_jwt = false

[functions.scrape-product-single]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.verify-review-password]
verify_jwt = false

[functions.scrape-faces]
verify_jwt = false

[functions.classify-face-gender]
verify_jwt = false

[functions.detect-faces]
verify_jwt = false

[functions.cluster-identities]
verify_jwt = false

[functions.classify-face-views]
verify_jwt = false

[functions.generate-face-crops]
verify_jwt = false

[functions.classify-all]
verify_jwt = false

[functions.organize-face-images]
verify_jwt = false

[functions.generate-outfit-description]
verify_jwt = false

[functions.generate-paired-images]
verify_jwt = false

[functions.detect-face-ai]
verify_jwt = false

[functions.upload-crop-references]
verify_jwt = false

[functions.upload-reference-images]
verify_jwt = false

[functions.crop-and-store-image]
verify_jwt = false

[functions.crop-look-head]
verify_jwt = false

[functions.generate-face-application]
verify_jwt = false

[functions.regenerate-output]
verify_jwt = false

[functions.expand-image-top]
verify_jwt = false

[functions.generate-more-outputs]
verify_jwt = false

[functions.regenerate-face-output]
verify_jwt = false

[functions.generate-clay-single]
verify_jwt = false

[functions.assign-role]
verify_jwt = false

[functions.resume-clay-job]
verify_jwt = false

[functions.resume-face-scrape]
verify_jwt = false

[functions.generate-repose-single]
verify_jwt = false

[functions.resume-repose-job]
verify_jwt = false

[functions.resume-pipeline-job]
verify_jwt = false

[functions.convert-tiff]
verify_jwt = false

[functions.process-repose-queue]
verify_jwt = false

[functions.generate-ai-apply]
verify_jwt = false

[functions.convert-image]
verify_jwt = false

[functions.detect-view-type]
verify_jwt = false
